version: '3'
services:
  app:
    container_name: duplo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    env_file:
      - .env 
    depends_on:
      - mongo
    networks:
      - duplo-network

  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - duplo-network

networks:
  duplo-network:
